# ----
# Site

title: Qencode
description: Jekyll template for API documentation.
url: https://example.com
google_analytics_key:
permalink: pretty

# -----
# Build

timezone: Etc/UTC

collections:
  overview:
    title: Overview
    position: 1
  tutorials:
    title: Tutorials
    position: 2
  apireference:
    title: API Reference
    position: 3
    output: false
  apiclients:
    title: API Clients
    position: 4
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "overview"
    values:
      _hide_content: true
  -
    scope:
      type: "tutorials"
    values:
      _hide_content: true
  -
    scope:
      type: "apireference"
    values:
      _hide_content: true
  -
    scope:
      type: "apiclients"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c#: C#
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby
  node: Node
  .net: .NET

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
